### ISSUE TITLE
[BUG] PyPI package missing required dependencies 

### ISSUE THREAD

**Issue by Tocic** [R1j1t/contextualSpellCheck#55]
**Describe the bug**
I can't install all the required dependencies using `pip install contextualSpellCheck`. It seems like [PyPI package](https://pypi.org/project/contextualSpellCheck/) doesn't contain [the fix](https://github.com/R1j1t/contextualSpellCheck/commit/4772e854c8417211d979eebd22aeea78a29e09cc#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).

**To Reproduce**
```shell
python -m venv venv
source venv/bin/activate
pip install contextualSpellCheck
python -c 'import contextualSpellCheck'
```
> ModuleNotFoundError: No module named 'torch'

**Expected behavior**
_torch_ and other deps autoinstallation.

**Version (please complete the following information):**
latest 0.4.0 contextualSpellCheck from PyPI.

**Additional information**
see #17 and https://github.com/R1j1t/contextualSpellCheck/pull/18.

**Comment by R1j1t** [comment]
I remember removing the `pytorch` package from deps because I saw that `contextualSpellCheck` another dependency `transformers` already had it in its setup.

See the below line in transformers: 
https://github.com/huggingface/transformers/blob/b0595d33c1b1abb75fc42a54553c724154cf6cd0/setup.py#L131

I am not sure why transformers library did not trigger the `pytorch` download. No worries, I will add it again as part of the dependency in `setup.py`. Thank you for pointing out this issue! Feel free to create a PR to fix this issue. By tomorrow I will update the dependencies and release the fix to PyPI. I will also try to investigate why `transformers` did not trigger `pytorch` download.
